function createfigure(zdata1)
%CREATEFIGURE(zdata1)
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 23-Dec-2020 11:55:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create mesh
mesh(zdata1,'Parent',axes1);

view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'off');
